language: python
cache: pip
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.6
    dist: xenial
env:
  matrix:
  - LOGGING=info
  global:
    secure: ypTGuhz/hF5UUB7zlor8ZvswxSpOs4m9Sp8A6jUFua/bVxRs4hO2NAXwkeZ919EPYE/tWuN5Gaa78vjeaidSCaIexBDCWRTsYjWpiSDK4OVu50O++qHeEYQWGi/+7h3v/qEaX1A+kpcegFx47WEhba8xT9kcVu/JjMLMJ8vicO2NLpE2RR3bTggqHRWXL4AUIqNs6ZF0M4iZJvyHcHCKWDA5SRi0QDlcVvXPWzY03vmdYMItVLEpyPhA7p5gs10Vu+zlGSXqJhLvveqLDUA430VTaM1CArRmIbeXnqQYxIV5fC6t5Mh3ChK8RvT8rU3CxNQI5koLTYaiCbJY59NelMzj9Yf41Z/JdADGe4jCCLRy5DVCd/HLcH7rVbV+cuyp6MzQetohRCoWxIvFIrTj6EoTavM8L2aEO4L0bM2NkCXQNI8v6mvSDkWz2404JlIMxP+GsvUFSg9X9/7eOaESTwAgOIXROIj3dOn8pyHygvOsxvvHLUbTk6zSdtqY7r0HKyjgQ6MplR6zAm1yN7KlIaDpq6anuqEb2+mbTdbC2y9/bbf+pdmHav3uKX9xspZnHYyHRV7IqrB9pB2R69YaxcpBV/SaTgjM00CRN8x4+KEXz7o+Z/6zrgzeHcbCTo8XQf4qwPDqfHYblvhCz/mcJAY0dXXQ3adLXuLn1PlUdd4=
install:
- pip install pip --upgrade
- pip install pybind11
- pip install -e git+https://github.com/XanaduAI/pennylane.git#egg=pennylane
- pip install -r requirements.txt
- pip install wheel pytest pytest-cov codecov --upgrade
- python3 setup.py bdist_wheel
- pip install dist/PennyLane*.whl
script:
- make coverage
after_success:
- codecov
notifications:
  slack:
    secure: FfvzFoLEPy+O1hkz+co7W/P2DAeGTqUYRTh7cA90wkhZNN+qHBXdhKzNOAZs4V462/AHHi13K95ltBCuW9nE6eJveZGQkPlLr9ojZtVKzIzNP2TgpnYRdAhogW1cmRdquPcPUXNBfs71DOPFTI2J8Kr1U3uZNkJ0HSURPlF05M11ESXPMzeMSNMjCAanFD+62+hsV8Jsx7vmLtiTCpMbatTgKYB/IE3nV2khILWMGcokxX5cSJ1/RRittLWMqLrmUPZnZ3f5G6YbkeV40Z//1/DK2/Mgw4ryZzZzCe3L4HQMxry5YeCJucnfGJmqJzRzB+JxNn0gRT4RX4SCJJBAa6BISwVvP89HFN5tkXGl8RYsKBJ0sdzbwQ0MFnS4rVoQP1IEAkx+TZ3fUzPZ68KDhspSxght6H+oRQCcaNFoHjh6xJSvAJQem6BQVyGErcjrmoxcPWmdNfiLs8lENcBSbN8fiZia8leCo5jzyl7dvBtlkRgvtx9pLSkevDLbPDMPVQokmXuVIG3psKCPZuAGAUTOP/FRYlZXCmXALsNAe7nuetXUSKL6P0YlA5PNPzstDEKe0LX50eiQV2olPPuLYed/Z6v7/VVIV4jgUXYVbnhbjY+g4pL1ikg58kbBY6afxXW4AGpvYoFEgdVmlBTvldlIXl84n3lH5hBHIVQiLiY=
